#!/usr/bin/perl
use strict;        # insist that all variables be declared
use diagnostics;   # expand the cryptic warnings
undef $/; # undefines the separator. Can read one whole file in one scalar.
MAIN:{

  # A little script to take the licence and put it at the top 
  # of every file.

  open(FILE, "<License.txt");
  my $license = join("", <FILE>);
  close(FILE);
  $license =~ s/\s*$//g;
  $license .= "\n";
  print "$license\n";
  
  my @files = (<*/*cc>, <*/*.cpp>, <*/*.h>);
  foreach my $file (@files){
    print "$file\n";
    open(FILE, "<$file");
    my $text = join("", <FILE>);
    $text =~ s/^.*?(\#)/$1/sg;
    $text = $license . $text;
    open(FILE, ">$file");
    print FILE $text;
    close(FILE);
  }
  
}
